# Generated by Django 4.2.13 on 2024-05-12 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UnderWater', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
