# Generated by Django 4.2.13 on 2024-06-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("BackManage", "0003_delete_showuser_alter_device_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="on",
            field=models.SmallIntegerField(default=0),
        ),
    ]
