# Generated by Django 4.2.13 on 2024-06-22 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Water",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("time", models.DateTimeField(auto_now_add=True)),
                ("type", models.CharField(max_length=20)),
                ("temperature", models.FloatField()),
                ("ph", models.FloatField()),
                (
                    "dissolved_oxygen",
                    models.FloatField(help_text="单位: mg/L", verbose_name="溶氧量"),
                ),
                (
                    "conductivity",
                    models.FloatField(help_text="单位: μS/cm", verbose_name="电导率"),
                ),
                (
                    "turbidity",
                    models.FloatField(help_text="单位: NTU", verbose_name="浊度"),
                ),
                (
                    "permanganate_index",
                    models.FloatField(help_text="单位: mg/L", verbose_name="高锰酸盐指数"),
                ),
                (
                    "ammonia_nitrogen",
                    models.FloatField(help_text="单位: mg/L", verbose_name="氨氮"),
                ),
                (
                    "total_phosphorus",
                    models.FloatField(help_text="单位: mg/L", verbose_name="总磷"),
                ),
                (
                    "total_nitrogen",
                    models.FloatField(help_text="单位: mg/L", verbose_name="总氮"),
                ),
            ],
        ),
    ]
